// <auto-generated />
using BowlingLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BowlingLib.Migrations
{
    [DbContext(typeof(BowlingContext))]
    [Migration("20171109101338_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BowlingLib.Model.Competition", b =>
                {
                    b.Property<int>("CompetitionId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("CompetitionId");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("BowlingLib.Model.CompetitionMember", b =>
                {
                    b.Property<int>("CompetitionMemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompetitionId");

                    b.Property<int>("MemberId");

                    b.Property<decimal>("WinRatio");

                    b.HasKey("CompetitionMemberId");

                    b.ToTable("CompetitionMember");
                });

            modelBuilder.Entity("BowlingLib.Model.Lane", b =>
                {
                    b.Property<int>("LaneId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("LaneId");

                    b.ToTable("Lane");
                });

            modelBuilder.Entity("BowlingLib.Model.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompetitionId");

                    b.Property<int>("WinnerId");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("BowlingLib.Model.MatchMember", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsVictory");

                    b.Property<int>("MemberId");

                    b.Property<int>("Score");

                    b.HasKey("MatchId");

                    b.ToTable("MatchMember");
                });

            modelBuilder.Entity("BowlingLib.Model.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("MemberId");

                    b.ToTable("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
